title:              Dani.is
email:              danijeon.ux@gmail.com
description:        Portfolio | Dani is a UX Designer 
author:             Dani J
baseurl:            ""
url:                "http://127.0.0.1:4000/"

# Social Profiles
twitter_username:   
github_username:    haayany
facebook_username:  
instagram_username:  
linkedin_username: danijeon

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
